export const tests = [
  {
    id: 1,
    category: "piima",
    title: "Test 3 - Prezident maktabi (Asosiy imtihon)",
    rating: 4.7,
    students: 13,
    duration: 130,
    isFree: false,
    price: "39,000",
    image: "/src/assets/piima-logo.webp",
  },
  {
    id: 2,
    category: "piima",
    title: "Test 2 - Prezident maktabi (Asosiy imtihon)",
    rating: 5.0,
    students: 10,
    duration: 130,
    isFree: false,
    price: "39,000",
    image: "/src/assets/piima-logo.webp",
  },
  {
    id: 3,
    category: "piima",
    title: "Test 1 - Prezident maktabi (Asosiy imtihon)",
    rating: 5.0,
    students: 201,
    duration: 130,
    isFree: false,
    price: "39,000",
    image: "/src/assets/piima-logo.webp",
  },

  {
    id: 4,
    category: "piima",
    title: "Test 3 - Prezident maktabi (Saralash bosqichi)",
    rating: 5.0,
    students: 14,
    duration: 60,
    isFree: false,
    price: "29,000",
    image: "/src/assets/piima-logo.webp",
  },
  {
    id: 5,
    category: "piima",
    title: "Test 3 - Al-Xorazmiy hamda ixtisoslashtirilgan maktab",
    rating: 4.3,
    students: 26,
    duration: 90,
    isFree: false,
    price: "39,000",
    image: "/src/assets/al-xorazmiy-logo.webp",
  },
  {
    id: 6,
    category: "piima",
    title: "Test 3 - Mirzo Ulug‘bek maktabi",
    rating: 5.0,
    students: 17,
    duration: 90,
    isFree: false,
    price: "39,000",
    image: "/src/assets/mirzo-ulugbek-maktabi.webp",
  },
  {
    id: 7,
    category: "piima",
    title: "Test 2 - Prezident maktabi (Saralash bosqichi)",
    rating: 5.0,
    students: 75,
    duration: 60,
    isFree: false,
    price: "29,000",
    image: "/src/assets/piima-logo.webp",
  },
  {
    id: 8,
    category: "piima",
    title: "Test 2 - Al-Xorazmiy hamda ixtisoslashtirilgan maktab",
    rating: 4.3,
    students: 259,
    duration: 90,
    isFree: false,
    price: "39,000",
    image: "/src/assets/al-xorazmiy-logo.webp",
  },
  {
    id: 9,
    category: "piima",
    title: "Test 2 - Mirzo Ulug‘bek maktabi",
    rating: 3.9,
    students: 17,
    duration: 90,
    isFree: false,
    price: "39,000",
    image: "/src/assets/mirzo-ulugbek-maktabi.webp",
  },
  {
    id: 10,
    category: "piima",
    title: "Test 1 - Prezident maktabi (Saralash bosqichi)",
    rating: 4.8,
    students: 1131,
    duration: 60,
    isFree: false,
    price: "29,000",
    image: "/src/assets/piima-logo.webp",
  },
  {
    id: 11,
    category: "piima",
    title: "Test 1 - Al-Xorazmiy hamda ixtisoslashtirilgan maktab",
    rating: 4.0,
    students: 11,
    duration: 90,
    isFree: false,
    price: "39,000",
    image: "/src/assets/al-xorazmiy-logo.webp",
  },
  {
    id: 12,
    category: "piima",
    title: "Test 1 - Mirzo Ulug‘bek maktabi",
    rating: 5.0,
    students: 144,
    duration: 90,
    isFree: false,
    price: "39,000",
    image: "/src/assets/mirzo-ulugbek-maktabi.webp",
  },
  {
    id: 13,
    category: "university",
    title: "Turin Foundation",
    rating: 4.1,
    students: 2886,
    duration: 72,
    isFree: true,
    image: "/src/assets/turin_logo.jpeg",
  },
  {
    id: 14,
    category: "university",
    title: "Test 2023",
    rating: 4.3,
    students: 13111,
    duration: 60,
    isFree: true,
    image: "/src/assets/bba-logo.webp",
  },
  {
    id: 15,
    category: "university",
    title: "Test 2022",
    rating: 4.4,
    students: 2667,
    duration: 60,
    isFree: true,
    image: "/src/assets/bba-logo.webp",
  },
  {
    id: 16,
    category: "university",
    title: "Test 2021",
    rating: 4.3,
    students: 4012,
    duration: 60,
    isFree: true,
    image: "/src/assets/bba-logo.webp",
  },

  {
    id: 17,
    category: "university",
    title: "Imtihon 2024",
    rating: 4.2,
    students: 1766,
    duration: 60,
    isFree: true,
    image: "/src/assets/bba-logo.webp",
  },
  {
    id: 18,
    category: "national",
    title: "Milliy sertifikat - Namuna",
    rating: 4.3,
    students: 11973,
    duration: 150,
    isFree: true,
    image: "/src/assets/milliy-sertifikat-logo.webp",
  },
  {
    id: 19,
    category: "national",
    title: "Milliy sertifikat - Mock test",
    rating: 3.7,
    students: 119,
    duration: 150,
    isFree: false,
    price: "50,000",
    image: "/src/assets/milliy-sertifikat-logo.webp",
  },
  {
    id: 20,
    category: "school",
    title: "2-sinf",
    rating: 4.7,
    students: 59717,
    duration: 45,
    isFree: true,
    image: "/src/assets/testbor-mini-logo.png",
  },
  {
    id: 21,
    category: "school",
    title: "3-sinf",
    rating: 4.7,
    students: 42532,
    duration: 45,
    isFree: true,
    image: "/src/assets/testbor-mini-logo.png",
  },
  {
    id: 22,
    category: "school",
    title: "4-sinf",
    rating: 4.5,
    students: 36986,
    duration: 45,
    isFree: true,
    image: "/src/assets/testbor-mini-logo.png",
  },
  {
    id: 23,
    category: "school",
    title: "5-sinf",
    rating: 4.4,
    students: 33184,
    duration: 45,
    isFree: true,
    image: "/src/assets/testbor-mini-logo.png",
  },
  {
    id: 24,
    category: "school",
    title: "6-sinf",
    rating: 4.2,
    students: 19758,
    duration: 45,
    isFree: true,
    image: "/src/assets/testbor-mini-logo.png",
  },
  {
    id: 25,
    category: "school",
    title: "7-sinf",
    rating: 4.2,
    students: 13446,
    duration: 45,
    isFree: true,
    image: "/src/assets/testbor-mini-logo.png",
  },
  {
    id: 26,
    category: "school",
    title: "8-sinf",
    rating: 4.2,
    students: 6761,
    duration: 45,
    isFree: true,
    image: "/src/assets/testbor-mini-logo.png",
  },
  {
    id: 27,
    category: "school",
    title: "9-sinf",
    rating: 3.9,
    students: 3541,
    duration: 45,
    isFree: true,
    image: "/src/assets/testbor-mini-logo.png",
  },
  {
    id: 28,
    category: "school",
    title: "10-sinf",
    rating: 4.0,
    students: 3758,
    duration: 45,
    isFree: true,
    image: "/src/assets/testbor-mini-logo.png",
  },
  {
    id: 29,
    category: "school",
    title: "11-sinf",
    rating: 4.2,
    students: 4910,
    duration: 45,
    isFree: true,
    image: "/src/assets/testbor-mini-logo.png",
  },
];
